-- Add face_embedding column to public.siswa table if not exists
ALTER TABLE public.siswa ADD COLUMN IF NOT EXISTS face_embedding TEXT;

-- Add face_embedding column to public.profiles table if not exists
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS face_embedding TEXT;

-- Add comment explaining format (Comma-separated 128 float values generated by face-api.js)
COMMENT ON COLUMN public.siswa.face_embedding IS 'Vektor 128-float embedding wajah dalam format string dipisahkan koma';
